### ISSUE TITLE
future cannot be sent between threads safely

### ISSUE THREAD

**Issue by antonengelhardt** [TmLev/crud-rest-api-rust-rocket-diesel-postgres#1]
Hi,

i am trying to build a backend with rocket.rs and diesel for db purposed. I found your repo and found it quite helpful.

However, i find an error (that i am stuck with for about a week now)... I compared your repo with mine and found that they are nearly the same except for the models.

For me its throwing the error "future cannot be sent between threads safely":

![Screenshot-CleanShot-006078](https://github.com/TmLev/crud-rest-api-rust-rocket-diesel-postgres/assets/106314688/56cd332a-27f3-4034-9d93-6cd6c5b5cef3)

Do you have any idea? :)

**Comment by TmLev** [comment]
Hey!

Not sure which versions of crates and the Rust compiler you're using, so there could be many reasons.

I'd also recommend using `axum`+`sqlx` instead of `rocket`+`diesel`.

**Comment by antonengelhardt** [comment]
@TmLev Ok, thanks. Will look into Axum and potentially switch as we have not developed anything yet. cc: @Vinni2001
